[phases.setup]
nixPkgs = ["nodejs_22", "bun"]
nixLibs = ["gcc-unwrapped"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]
cacheDirectories = [
  "/root/.bun",
  "node_modules",
  ".next/cache"
]

[phases.build]
cmds = [
  "echo '🏗 Starting build phase...'",
  "bun run build"
]
cacheDirectories = [
  ".next/cache"
]

[phases.start]
cmd = "bun run start"

[cache]
paths = ["node_modules", ".next/cache"]
