[phases.setup]
nixPkgs = ["bun", "git"]  # Incluye Bun desde nixpkgs

[phases.install]
cmds = ["bun install --frozen-lockfile"]
cacheDirectories = [
  "/root/.bun",
  "node_modules",
  ".next/cache"
]

[phases.build]
cacheDirectories = [
  ".next/cache"
]
cmds = [
  "echo '🏗 Starting build phase...'",
  "bun run build"
]

[phases.start]
cmd = "bun run start"

[cache]
paths = ["node_modules", ".next/cache"]
