[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'

[phases.setup]
nixPkgs = ['bun_1_2_13']
nixLibs = ['gcc-unwrapped']

[phases.install]
dependsOn = ['setup']
cmds = ['bun install --frozen-lockfile']
cacheDirectories = ['/root/.bun', 'node_modules']
paths = ['/app/node_modules/.bin']

[phases.build]
dependsOn = ['install']
cmds = ['bun run build']
cacheDirectories = ['.next/cache']

[start]
cmd = 'bun run start'
