/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    ciudadanos: CiudadanoAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    noticias: Noticia;
    imagenes: Imagen;
    curriculums: Curriculum;
    archivos: Archivo;
    'archivos-obras': ArchivosObra;
    avatares: Avatar;
    memorias: Memoria;
    contabilidad: Contabilidad;
    intimaciones: Intimacione;
    ubicaciones: Ubicacione;
    eventos: Evento;
    habilitaciones: Habilitacione;
    licitaciones: Licitacione;
    concursos: Concurso;
    'balances-mensuales': BalancesMensuale;
    'eventos-tags': EventosTag;
    ciudadanos: Ciudadano;
    matriculados: Matriculado;
    'rubros-comercios': RubrosComercio;
    'comercios-habilitados': ComerciosHabilitado;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    ciudadanos: {
      curriculum: 'curriculums';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    noticias: NoticiasSelect<false> | NoticiasSelect<true>;
    imagenes: ImagenesSelect<false> | ImagenesSelect<true>;
    curriculums: CurriculumsSelect<false> | CurriculumsSelect<true>;
    archivos: ArchivosSelect<false> | ArchivosSelect<true>;
    'archivos-obras': ArchivosObrasSelect<false> | ArchivosObrasSelect<true>;
    avatares: AvataresSelect<false> | AvataresSelect<true>;
    memorias: MemoriasSelect<false> | MemoriasSelect<true>;
    contabilidad: ContabilidadSelect<false> | ContabilidadSelect<true>;
    intimaciones: IntimacionesSelect<false> | IntimacionesSelect<true>;
    ubicaciones: UbicacionesSelect<false> | UbicacionesSelect<true>;
    eventos: EventosSelect<false> | EventosSelect<true>;
    habilitaciones: HabilitacionesSelect<false> | HabilitacionesSelect<true>;
    licitaciones: LicitacionesSelect<false> | LicitacionesSelect<true>;
    concursos: ConcursosSelect<false> | ConcursosSelect<true>;
    'balances-mensuales': BalancesMensualesSelect<false> | BalancesMensualesSelect<true>;
    'eventos-tags': EventosTagsSelect<false> | EventosTagsSelect<true>;
    ciudadanos: CiudadanosSelect<false> | CiudadanosSelect<true>;
    matriculados: MatriculadosSelect<false> | MatriculadosSelect<true>;
    'rubros-comercios': RubrosComerciosSelect<false> | RubrosComerciosSelect<true>;
    'comercios-habilitados': ComerciosHabilitadosSelect<false> | ComerciosHabilitadosSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    autoridades: Autoridade;
  };
  globalsSelect: {
    autoridades: AutoridadesSelect<false> | AutoridadesSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Ciudadano & {
        collection: 'ciudadanos';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CiudadanoAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  rol: ('ADMIN' | 'COMUNICACION' | 'HABILITACIONES' | 'HACIENDA' | 'JUZGADO' | 'GESTOR CIUDADANO' | 'OBRAS PRIVADAS')[];
  activo?: boolean | null;
  avatar?: (string | null) | Avatar;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatares".
 */
export interface Avatar {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ciudadanos".
 */
export interface Ciudadano {
  id: string;
  activo?: boolean | null;
  avatar?: (string | null) | Avatar;
  nombre?: string | null;
  apellido?: string | null;
  dni: string;
  domicilio?: string | null;
  fecha_nacimiento?: string | null;
  ciudad?: string | null;
  telefono?: string | null;
  curriculum?: {
    docs?: (string | Curriculum)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curriculums".
 */
export interface Curriculum {
  id: string;
  titulo?: string | null;
  ciudadano: string | Ciudadano;
  estudios?:
    | {
        institucion?: string | null;
        fecha_inicio?: string | null;
        fecha_finalizacion?: string | null;
        nivel?: ('PRIMARIO' | 'SECUNDARIO' | 'TERCIARIO' | 'GRADO' | 'POSTGRADO' | 'CURSO/TALLER') | null;
        descripcion?: string | null;
        is_old?: boolean | null;
        nivel_old?: string | null;
        id?: string | null;
      }[]
    | null;
  experiencias?:
    | {
        institucion?: string | null;
        fecha_inicio?: string | null;
        fecha_finalizacion?: string | null;
        puesto?: string | null;
        descripcion?: string | null;
        id?: string | null;
      }[]
    | null;
  referencias?:
    | {
        nombre?: string | null;
        telefono?: string | null;
        email?: string | null;
        descripcion?: string | null;
        id?: string | null;
      }[]
    | null;
  categorias?:
    | {
        nombre?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias".
 */
export interface Noticia {
  id: string;
  titulo: string;
  slug: string;
  descripcion: string;
  portada: string | Imagen;
  contenido?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  youtube_videos?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  archivos?: (string | Archivo)[] | null;
  is_old: boolean;
  contenido_old?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imagenes".
 */
export interface Imagen {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivos".
 */
export interface Archivo {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivos-obras".
 */
export interface ArchivosObra {
  id: string;
  alt: string;
  /**
   * Indica a qué sección pertenece este archivo
   */
  categoria: 'proyecto' | 'relevamiento';
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memorias".
 */
export interface Memoria {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  archivo: string | Archivo;
  nombre: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contabilidad".
 */
export interface Contabilidad {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  archivo: string | Archivo;
  nombre: string;
  fecha: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intimaciones".
 */
export interface Intimacione {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  archivo: string | Archivo;
  /**
   * Indicar nombres y apellidos completos del intimado
   */
  nombre: string;
  fecha: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ubicaciones".
 */
export interface Ubicacione {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  nombre: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  geolocalizacion?: [number, number] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos".
 */
export interface Evento {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  nombre: string;
  descripcion: string;
  fecha: string;
  ubicacion: string | Ubicacione;
  /**
   * Enlace a la página de entradas o información adicional
   */
  entradas: string;
  /**
   * Nombre de la organización o persona que organiza el evento
   */
  organiza: string;
  tags?: (string | EventosTag)[] | null;
  imagen?: (string | null) | Imagen;
  archivos?: (string | Archivo)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos-tags".
 */
export interface EventosTag {
  id: string;
  nombre: string;
  descripcion: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habilitaciones".
 */
export interface Habilitacione {
  id: string;
  nombre: string;
  contenido?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  adjuntos?: (string | Archivo)[] | null;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licitaciones".
 */
export interface Licitacione {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  titulo: string;
  descripcion: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  fecha: string;
  estado: 'en_proceso' | 'adjudicada' | 'cancelada';
  documento: string | Archivo;
  archivos_adicionales?:
    | {
        archivo: string | Archivo;
        descripcion?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concursos".
 */
export interface Concurso {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  titulo: string;
  descripcion: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  fecha: string;
  estado: 'abierto' | 'en_evaluacion' | 'finalizado' | 'cancelado';
  documento: string | Archivo;
  archivos_adicionales?:
    | {
        archivo: string | Archivo;
        descripcion?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "balances-mensuales".
 */
export interface BalancesMensuale {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  titulo: string;
  descripcion: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  fecha: string;
  tipo: 'balance_general' | 'estado_resultados' | 'flujo_efectivo' | 'otro';
  documento: string | Archivo;
  archivos_adicionales?:
    | {
        archivo: string | Archivo;
        descripcion?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matriculados".
 */
export interface Matriculado {
  id: string;
  dni: string;
  nombreCompleto: string;
  matricula: string;
  direccion: string;
  telefono: string;
  email: string;
  profesion: string;
  habilitado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rubros-comercios".
 */
export interface RubrosComercio {
  id: string;
  nombre: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comercios-habilitados".
 */
export interface ComerciosHabilitado {
  id: string;
  nombre: string;
  cuit: string;
  razonSocial: string;
  direccion: string;
  /**
   * Se puede obtener ubicando el punto en Google Maps y copiando las coordenadas que se muestran apretando clic derecho.
   *
   * @minItems 2
   * @maxItems 2
   */
  localizacion: [number, number];
  rubros?: (string | RubrosComercio)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'noticias';
        value: string | Noticia;
      } | null)
    | ({
        relationTo: 'imagenes';
        value: string | Imagen;
      } | null)
    | ({
        relationTo: 'curriculums';
        value: string | Curriculum;
      } | null)
    | ({
        relationTo: 'archivos';
        value: string | Archivo;
      } | null)
    | ({
        relationTo: 'archivos-obras';
        value: string | ArchivosObra;
      } | null)
    | ({
        relationTo: 'avatares';
        value: string | Avatar;
      } | null)
    | ({
        relationTo: 'memorias';
        value: string | Memoria;
      } | null)
    | ({
        relationTo: 'contabilidad';
        value: string | Contabilidad;
      } | null)
    | ({
        relationTo: 'intimaciones';
        value: string | Intimacione;
      } | null)
    | ({
        relationTo: 'ubicaciones';
        value: string | Ubicacione;
      } | null)
    | ({
        relationTo: 'eventos';
        value: string | Evento;
      } | null)
    | ({
        relationTo: 'habilitaciones';
        value: string | Habilitacione;
      } | null)
    | ({
        relationTo: 'licitaciones';
        value: string | Licitacione;
      } | null)
    | ({
        relationTo: 'concursos';
        value: string | Concurso;
      } | null)
    | ({
        relationTo: 'balances-mensuales';
        value: string | BalancesMensuale;
      } | null)
    | ({
        relationTo: 'eventos-tags';
        value: string | EventosTag;
      } | null)
    | ({
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      } | null)
    | ({
        relationTo: 'matriculados';
        value: string | Matriculado;
      } | null)
    | ({
        relationTo: 'rubros-comercios';
        value: string | RubrosComercio;
      } | null)
    | ({
        relationTo: 'comercios-habilitados';
        value: string | ComerciosHabilitado;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  rol?: T;
  activo?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "noticias_select".
 */
export interface NoticiasSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  descripcion?: T;
  portada?: T;
  contenido?: T;
  youtube_videos?:
    | T
    | {
        url?: T;
        id?: T;
      };
  archivos?: T;
  is_old?: T;
  contenido_old?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imagenes_select".
 */
export interface ImagenesSelect<T extends boolean = true> {
  created_by?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "curriculums_select".
 */
export interface CurriculumsSelect<T extends boolean = true> {
  titulo?: T;
  ciudadano?: T;
  estudios?:
    | T
    | {
        institucion?: T;
        fecha_inicio?: T;
        fecha_finalizacion?: T;
        nivel?: T;
        descripcion?: T;
        is_old?: T;
        nivel_old?: T;
        id?: T;
      };
  experiencias?:
    | T
    | {
        institucion?: T;
        fecha_inicio?: T;
        fecha_finalizacion?: T;
        puesto?: T;
        descripcion?: T;
        id?: T;
      };
  referencias?:
    | T
    | {
        nombre?: T;
        telefono?: T;
        email?: T;
        descripcion?: T;
        id?: T;
      };
  categorias?:
    | T
    | {
        nombre?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivos_select".
 */
export interface ArchivosSelect<T extends boolean = true> {
  created_by?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "archivos-obras_select".
 */
export interface ArchivosObrasSelect<T extends boolean = true> {
  alt?: T;
  categoria?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatares_select".
 */
export interface AvataresSelect<T extends boolean = true> {
  created_by?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memorias_select".
 */
export interface MemoriasSelect<T extends boolean = true> {
  created_by?: T;
  archivo?: T;
  nombre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contabilidad_select".
 */
export interface ContabilidadSelect<T extends boolean = true> {
  created_by?: T;
  archivo?: T;
  nombre?: T;
  fecha?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intimaciones_select".
 */
export interface IntimacionesSelect<T extends boolean = true> {
  created_by?: T;
  archivo?: T;
  nombre?: T;
  fecha?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ubicaciones_select".
 */
export interface UbicacionesSelect<T extends boolean = true> {
  created_by?: T;
  nombre?: T;
  geolocalizacion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos_select".
 */
export interface EventosSelect<T extends boolean = true> {
  created_by?: T;
  nombre?: T;
  descripcion?: T;
  fecha?: T;
  ubicacion?: T;
  entradas?: T;
  organiza?: T;
  tags?: T;
  imagen?: T;
  archivos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habilitaciones_select".
 */
export interface HabilitacionesSelect<T extends boolean = true> {
  nombre?: T;
  contenido?: T;
  adjuntos?: T;
  created_by?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "licitaciones_select".
 */
export interface LicitacionesSelect<T extends boolean = true> {
  created_by?: T;
  titulo?: T;
  descripcion?: T;
  fecha?: T;
  estado?: T;
  documento?: T;
  archivos_adicionales?:
    | T
    | {
        archivo?: T;
        descripcion?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "concursos_select".
 */
export interface ConcursosSelect<T extends boolean = true> {
  created_by?: T;
  titulo?: T;
  descripcion?: T;
  fecha?: T;
  estado?: T;
  documento?: T;
  archivos_adicionales?:
    | T
    | {
        archivo?: T;
        descripcion?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "balances-mensuales_select".
 */
export interface BalancesMensualesSelect<T extends boolean = true> {
  created_by?: T;
  titulo?: T;
  descripcion?: T;
  fecha?: T;
  tipo?: T;
  documento?: T;
  archivos_adicionales?:
    | T
    | {
        archivo?: T;
        descripcion?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventos-tags_select".
 */
export interface EventosTagsSelect<T extends boolean = true> {
  nombre?: T;
  descripcion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ciudadanos_select".
 */
export interface CiudadanosSelect<T extends boolean = true> {
  activo?: T;
  avatar?: T;
  nombre?: T;
  apellido?: T;
  dni?: T;
  domicilio?: T;
  fecha_nacimiento?: T;
  ciudad?: T;
  telefono?: T;
  curriculum?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matriculados_select".
 */
export interface MatriculadosSelect<T extends boolean = true> {
  dni?: T;
  nombreCompleto?: T;
  matricula?: T;
  direccion?: T;
  telefono?: T;
  email?: T;
  profesion?: T;
  habilitado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rubros-comercios_select".
 */
export interface RubrosComerciosSelect<T extends boolean = true> {
  nombre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comercios-habilitados_select".
 */
export interface ComerciosHabilitadosSelect<T extends boolean = true> {
  nombre?: T;
  cuit?: T;
  razonSocial?: T;
  direccion?: T;
  localizacion?: T;
  rubros?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autoridades".
 */
export interface Autoridade {
  id: string;
  created_by:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'ciudadanos';
        value: string | Ciudadano;
      };
  presidente: string;
  secretario: string;
  bloques?:
    | {
        nombre: string;
        concejales?:
          | {
              concejal?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autoridades_select".
 */
export interface AutoridadesSelect<T extends boolean = true> {
  created_by?: T;
  presidente?: T;
  secretario?: T;
  bloques?:
    | T
    | {
        nombre?: T;
        concejales?:
          | T
          | {
              concejal?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}